### PR TITLE
Add missing field to boxplot

### PR DESCRIPTION
**Pull request by yg0x01**
I have added some content to the BoxPlot based on the ECharts documentation. Currently, the BoxPlot can set data using the Dataset method, but this requires using ECharts' standard algorithm for box plots and inputting the raw data. If our programs have already calculated the box plot results, such as lower_whisker, q1, q2, q3, upper_whisker, and outliers, there is currently no way to set the data directly.

### CODE REVIEW

**Comment by LukaOber** [comment]
Would you be so kind and switch the setter for ItemStyle to `Into<Itemstyle>`?

Can you provide an example, just so we can check that the implementation of data is working? 

I believe the lint warnings are from new clippy features and have nothing to do with your PR. I will fix or ignore them in the coming days.

**Comment by humphreylee** [comment]
Probably a long shot comment here. I am facing similar issue for scatter plot - say I have x, y, color_style, size_style, group_id, etc. Thus, I made a macro (dz!) to pass all these data into Echarts in this [PR](https://github.com/yuankunzhang/charming/pull/100). It acts like df!, but handle many more data vectors.

**Comment by yg0x01** [comment]
> Would you be so kind and switch the setter for ItemStyle to `Into<Itemstyle>`?
> 
> Can you provide an example, just so we can check that the implementation of data is working?
> 
> I believe the lint warnings are from new clippy features and have nothing to do with your PR. I will fix or ignore them in the coming days.
Sure. Sorry for not checking this carefully. I will fix it as soon as possible.

**Comment by yg0x01** [comment]
> Probably a long shot comment here. I am facing similar issue for scatter plot - say I have x, y, color_style, size_style, group_id, etc. Thus, I made a macro (dz!) to pass all these data into Echarts in this [PR](https://github.com/yuankunzhang/charming/pull/100). It acts like df!, but handle many more data vectors.
. 
It looks great! There are indeed too many ECharts configurations that can be added to this repo. It would be very helpful to have a macro that allows for flexible addition of configurations.

**Comment by LukaOber** [comment]
> It looks great! There are indeed too many ECharts configurations that can be added to this repo. It would be very helpful to have a macro that allows for flexible addition of configurations.

I have written a proc macro which can expand to the setter pattern we are using. If you want, you can check it out or even review it #105

**Pull request merged**
