### PR TITLE
Add missing Candlestick OHLC example output

### PR DESCRIPTION
**Pull request by humphreylee**
Add missing Candlestick OHLC example output

### CODE REVIEW

**Comment by LukaOber** [comment]
I am hesitant to merge an example file which is 26k lines long. Wouldn't it be better to instead document how you can generate it?

**Comment by humphreylee** [comment]
> After a quick glance at the img folder I saw that the examples are svg files and not HTML. An SVG file would probably be wayy smaller. Especially if we reduce the amount of data. 

Yes, this html was generated from [this example](https://github.com/yuankunzhang/charming/blob/main/gallery%2Fsrc%2Fcandlestick%2Fohlc.rs). I can only do html output. Alternatively, I can do screenshots into png format. Unfortunately, I cannot get charming to output svg format on my locked down Windows machine.

**Comment by humphreylee** [comment]
What I appreciate about this example is how it demonstrates creating error bars, a feature not yet available in the upstream ECharts.

**Comment by humphreylee** [comment]
Please hold on for now; I think the README should also be updated to link this image to its source.

**Comment by humphreylee** [comment]
If you are fine with placing this example under "Custom Charts", it should be ready to merge.

**Comment by LukaOber** [comment]
Are you able to remove the zoom element at the bottom and the toolbox at the top right? They are not relevant in an SVG.

**Comment by humphreylee** [comment]
> Are you able to remove the zoom element at the bottom and the toolbox at the top right? They are not relevant in an SVG.

Done.

**Comment by LukaOber** [comment]
Thank you very much for keeping up with my requests. LGTM

**Pull request merged**
