### PR TITLE
Use `resvg` and `image` crates for SSR

### PR DESCRIPTION
**Pull request by Hpmason**
Hi, I really like what you've done with the project, but I've had difficulties using it on Windows with its gdk-pixbuf dependency. This switch would remove the need for gdk as a build dependency, making it easier to build. It also allows for a wider range of output image formats (e.g. .bmp).

I hope you find this useful, but I understand if this is not the direction you want to go with your library. If there's any changes I can make, I'd be happy to make them!

### CODE REVIEW

**Comment by yuankunzhang** [comment]
Hi @Hpmason , awesome work! That is definitely my planned direction, actually I've already been considering the `resvg` library. I'm glad that you are helping out! Please go ahead to make this happen. Btw you can run `cargo run --bin generate_images /tmp/images` to generate all the examples into images.

**Comment by Hpmason** [comment]
Glad I can help! This PR should be ready for review, when you get the chance

**Comment by yuankunzhang** [comment]
That's great work! For some reasons, when I render charts to non-svg images, the texts are missing. Does the text rendering work on Windows?

**Comment by Hpmason** [comment]
Sorry, my bad. [resvg docs](https://docs.rs/resvg/latest/resvg/struct.Tree.html#method.from_usvg) mention that text needs to be converted before converting to a resvg::Tree. I just pushed a fix that works on Windows

**Pull request merged**
